version: '3.3'

services:
  liho:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./public_html:/var/www/html
