version: '3.3'

services:
  php:
    container_name: liho-docker-image-php-apache
    image: lehungio/php-apache
    entrypoint: php -S 0.0.0.0:8000
    working_dir: /code
    ports:
      - "8000:8000"
    volumes:
      - /path/to/your/app:/code
