version: '3.3'

services:
  php:
    container_name: liho-docker-image-php-apache
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./:/code
